#!/bin/bash
apatop=/devel/00mirror-sf/pdf
jars="."
addjar(){
jars="$jars:$1"
}
for aa in $apatop/*.jar; do
    addjar $aa
done
addjar /devel/lib/java/javax.xml.bind-2.2.3.jar
addjar /devel/lib/java/java.activation-1.1.1.jar
java -cp $jars \
PDFValidate $*
