#!/bin/bash
cert=ca/demo2_user1.p12
certpass=1234
thisdir=`dirname $0`
jars="$thisdir"
addjar(){
jars="$jars:$1"
}
for fname in $thisdir/java/*.jar; do
    addjar $fname
done
java -cp $jars \
org.apache.pdfbox.examples.signature.CreateSignature \
$cert $certpass $1
