#!/bin/bash
thisdir=`dirname $0`
jars="$thisdir"
addjar(){
jars="$jars:$1"
}
for fname in $thisdir/java/*.jar; do
    addjar $fname
done
java -cp $jars: org.apache.pdfbox.examples.signature.ShowSignature "" $1
