#!/bin/bash
cert=/home/mak/Dokumenty/m32/ssl/cert.p12
#cert=demo2_user1.p12
thisdir=`dirname $0`
jars="$thisdir"
addjar(){
jars="$jars:$1"
}
for fname in $thisdir/java/*.jar; do
    addjar $fname
done
java -cp $jars \
PDFSign \
-k $cert 1234 -i $1
