#!/bin/bash

one() {
vpy3 pyhanko \
--verbose \
sign validate \
--no-revocation-check \
--pretty-print \
--trust ./nccert2016.crt.pem \
$*
}

#one pdf-signed-cms.pdf
#one pdf-signed-cms-m32-unizeto.pdf
one $*
