#!/bin/bash

full() {
vpy3 pyhanko \
--verbose \
sign validate \
--pretty-print \
$*
}

fast() {
full \
--no-revocation-check \
$*
}


#pdf-verifier-pyhanko fast pdf-signed-cms.pdf
#pdf-verifier-pyhanko fast pdf-signed-cms-m32-unizeto.pdf
$*
